language: python
python:
 - 3.5

sudo: required
dist: trusty

install:
 - pip install django flake8

script:
 - python manage.py migrate
 - python manage.py test

deploy:
 provider: heroku
 api-key:
 app: gcs01-thiagofelix-travis
